// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbAirbnbs
    {
        public tbAirbnbs()
        {
            tbFotografiasPorAirbnbs = new HashSet<tbFotografiasPorAirbnbs>();
        }

        public int Airb_Id { get; set; }
        public string Airb_Nombre { get; set; }
        public string Airb_DireccionExacta { get; set; }
        public decimal Airb_PrecioTodoIncluido { get; set; }
        public decimal? Airb_Precio { get; set; }
        public int? Airb_NumCamas { get; set; }
        public string Airb_Resena { get; set; }
        public string Airb_Correo { get; set; }
        public int? Airb_Telefono { get; set; }
        public int? Airb_NumHabitaciones { get; set; }
        public string Airb_Imagen { get; set; }
        public string Ciud_Id { get; set; }
        public int? Airb_Usua_Creacion { get; set; }
        public DateTime? Airb_Fecha_Creacion { get; set; }
        public int? Airb_Usua_Modifica { get; set; }
        public DateTime? Airb_Fecha_Modifica { get; set; }
        public bool? Airb_Estado { get; set; }
        [NotMapped]
        public string Ciud_Descripcion { get; set; }
        [NotMapped]
        public string Esta_Descripcion { get; set; }
        [NotMapped]
        public string Pais_Descripcion { get; set; }

        public virtual tbUsuarios Airb_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Airb_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbFotografiasPorAirbnbs> tbFotografiasPorAirbnbs { get; set; }
    }
}