// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbCargos
    {
        public tbCargos()
        {
            tbPersonas = new HashSet<tbPersonas>();
        }

        public int Carg_Id { get; set; }
        public string Carg_Descripcion { get; set; }
        public int? Carg_Usua_Creacion { get; set; }
        public DateTime? Carg_Fecha_Creacion { get; set; }
        public int? Carg_Usua_Modifica { get; set; }
        public DateTime? Carg_Fecha_Modifica { get; set; }

        public virtual tbUsuarios Carg_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Carg_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbPersonas> tbPersonas { get; set; }
    }
}