// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbCiudades
    {
        public int Ciud_Id { get; set; }
        public string Ciud_Codigo { get; set; }
        public string Ciud_Descripcion { get; set; }
        public int? Esta_Id { get; set; }
        public int? Ciud_Usua_Creacion { get; set; }
        public DateTime? Ciud_Fecha_Creacion { get; set; }
        public int? Ciud_Usua_Modifica { get; set; }
        public DateTime? Ciud_Fecha_Modifica { get; set; }
    }
}