// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbCiudades
    {
        public tbCiudades()
        {
            tbHoteles = new HashSet<tbHoteles>();
            tbPersonas = new HashSet<tbPersonas>();
            tbTransportesTran_PuntoFinalNavigation = new HashSet<tbTransportes>();
            tbTransportesTran_PuntoInicioNavigation = new HashSet<tbTransportes>();
        }

        public string Ciud_Id { get; set; }
        public string Ciud_Descripcion { get; set; }
        public string Esta_Id { get; set; }
        public int? Ciud_Usua_Creacion { get; set; }
        public DateTime? Ciud_Fecha_Creacion { get; set; }
        public int? Ciud_Usua_Modifica { get; set; }
        public DateTime? Ciud_Fecha_Modifica { get; set; }

        public virtual tbEstados Esta { get; set; }
        public virtual ICollection<tbHoteles> tbHoteles { get; set; }
        public virtual ICollection<tbPersonas> tbPersonas { get; set; }
        public virtual ICollection<tbTransportes> tbTransportesTran_PuntoFinalNavigation { get; set; }
        public virtual ICollection<tbTransportes> tbTransportesTran_PuntoInicioNavigation { get; set; }
    }
}