// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbDetallePorPaquete
    {
        public int DePa_Id { get; set; }
        public int HaHo_Tran_Id { get; set; }
        public decimal DePa_Precio { get; set; }
        public int Paqu_Id { get; set; }
        public int DePa_Usua_Creacion { get; set; }
        public DateTime DePa_Fecha_Creacion { get; set; }
        public int DePa_Usua_Modifica { get; set; }
        public DateTime DePa_Fecha_Modifica { get; set; }
        public int? DePa_Cantidad { get; set; }
        public int? DePa_NumNoches { get; set; }
        public decimal DePa_PrecioTodoIncluido { get; set; }

        public virtual tbUsuarios DePa_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios DePa_Usua_ModificaNavigation { get; set; }
        public virtual tbPaquetes Paqu { get; set; }
    }
}