// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbEstadosCiviles
    {
        public tbEstadosCiviles()
        {
            tbClientes = new HashSet<tbClientes>();
        }

        public int EsCi_Id { get; set; }
        public string EsCi_Descripcion { get; set; }
        public int? EsCi_Usua_Creacion { get; set; }
        public DateTime? EsCi_Fecha_Creacion { get; set; }
        public int? EsCi_Usua_Modifica { get; set; }
        public DateTime? EsCi_Fecha_Modifica { get; set; }
        public bool? EsCi_Estado { get; set; }

        public virtual tbUsuarios EsCi_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios EsCi_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientes { get; set; }
    }
}