// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbEstados
    {
        public tbEstados()
        {
            tbCiudades = new HashSet<tbCiudades>();
        }

        public string Esta_Id { get; set; }
        public string Esta_Descripcion { get; set; }
        public int? Esta_Usua_Creacion { get; set; }
        public DateTime? Esta_Fecha_Creacion { get; set; }
        public int? Esta_Usua_Modifica { get; set; }
        public DateTime? Esta_Fecha_Modifica { get; set; }
        public int? Pais_Id { get; set; }

        public virtual tbUsuarios Esta_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Esta_Usua_ModificaNavigation { get; set; }
        public virtual tbPaises Pais { get; set; }
        public virtual ICollection<tbCiudades> tbCiudades { get; set; }
    }
}