// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbFacturas
    {
        public tbFacturas()
        {
            tbFacturasDetalles = new HashSet<tbFacturasDetalles>();
        }

        public int Fact_Id { get; set; }
        public DateTime? Fact_Fecha { get; set; }
        public int? Meto_Id { get; set; }
        public int? Pago_Id { get; set; }
        public int? Pers_Id { get; set; }
        public int? Fact_Usua_Creacion { get; set; }
        public DateTime? Fact_Fecha_Creacion { get; set; }
        public int? Fact_Usua_Modifica { get; set; }
        public DateTime? Fact_Fecha_Modifica { get; set; }
        public bool Fact_Emitida { get; set; }

        public virtual tbUsuarios Fact_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Fact_Usua_ModificaNavigation { get; set; }
        public virtual tbMetodosPagos Meto { get; set; }
        public virtual tbPersonas Pers { get; set; }
        public virtual ICollection<tbFacturasDetalles> tbFacturasDetalles { get; set; }
    }
}