// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbFacturasDetalles
    {
        public int Fdet_Id { get; set; }
        public int? Fact_Id { get; set; }
        public int? Paqu_Id { get; set; }
        public int Fact_CantidadPaqu { get; set; }

        public virtual tbFacturas Fact { get; set; }
        public virtual tbPaquetes Paqu { get; set; }
    }
}