// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbFotografiasPorAirbnbs
    {
        public int FoAi_Id { get; set; }
        public string FoAi_UrlImagen { get; set; }
        public int? Airb_Id { get; set; }

        public virtual tbAirbnbs Airb { get; set; }
    }
}