// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbHabitaciones
    {
        public tbHabitaciones()
        {
            tbHabitacionesCategorias = new HashSet<tbHabitacionesCategorias>();
        }

        public int Habi_Id { get; set; }
        public int Habi_NumCamas { get; set; }
        public int Habi_NumPersonas { get; set; }
        public int TiCa_Id { get; set; }
        public int Habi_Usua_Creacion { get; set; }
        public DateTime Habi_Fecha_Creacion { get; set; }
        public int? Habi_Usua_Modifica { get; set; }
        public DateTime? Habi_Fecha_Modifica { get; set; }
        public int Habi_Estado { get; set; }

        public virtual tbUsuarios Habi_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Habi_Usua_ModificaNavigation { get; set; }
        public virtual tbTiposDeCamas TiCa { get; set; }
        public virtual ICollection<tbHabitacionesCategorias> tbHabitacionesCategorias { get; set; }
    }
}