// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbHabitacionesPorHotel
    {
        public tbHabitacionesPorHotel()
        {
            tbFotografiasPorHabitacion = new HashSet<tbFotografiasPorHabitacion>();
        }

        public int HaHo_Id { get; set; }
        public decimal HaHo_PrecioPorNoche { get; set; }
        public decimal HaHo_CargoExtraPersona { get; set; }
        public int Hote_Id { get; set; }
        public int Habi_Id { get; set; }

        public virtual tbHabitaciones Habi { get; set; }
        public virtual tbHoteles Hote { get; set; }
        public virtual ICollection<tbFotografiasPorHabitacion> tbFotografiasPorHabitacion { get; set; }
    }
}