// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbHorariosTransportes
    {
        public int HorT_Id { get; set; }
        public DateTime HorT_FechaYhora { get; set; }
        public int Tran_Id { get; set; }

        public virtual tbTransportes Tran { get; set; }
    }
}