// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbHoteles
    {
        public tbHoteles()
        {
            tbHabitacionesPorHotel = new HashSet<tbHabitacionesPorHotel>();
        }

        public int Hote_Id { get; set; }
        public string Hote_Nombre { get; set; }
        public string Hote_DireccionExacta { get; set; }
        public TimeSpan Hote_HoraSalida { get; set; }
        public decimal Hote_PrecioTodoIncluido { get; set; }
        public int Hote_Estrellas { get; set; }
        public string Hote_Imagen { get; set; }
        public string Ciud_Id { get; set; }
        public int Hote_Usua_Creacion { get; set; }
        public DateTime Hote_Fecha_Creacion { get; set; }
        public int Hote_Usua_Modifica { get; set; }
        public DateTime Hote_Fecha_Modifica { get; set; }
        public int Hote_Estado { get; set; }

        public virtual tbCiudades Ciud { get; set; }
        public virtual tbUsuarios Hote_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Hote_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbHabitacionesPorHotel> tbHabitacionesPorHotel { get; set; }
    }
}