// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbHoteles
    {
        public tbHoteles()
        {
            tbHabitacionesCategorias = new HashSet<tbHabitacionesCategorias>();
        }

        public int Hote_Id { get; set; }
        public string Hote_Nombre { get; set; }
        public string Hote_DireccionExacta { get; set; }
        public TimeSpan Hote_HoraSalida { get; set; }
        public decimal Hote_PrecioTodoIncluido { get; set; }
        public int Hote_Estrellas { get; set; }
        public string Hote_Imagen { get; set; }
        public string Ciud_Id { get; set; }
        public int Hote_Usua_Creacion { get; set; }
        public DateTime Hote_Fecha_Creacion { get; set; }
        public int? Hote_Usua_Modifica { get; set; }
        public DateTime? Hote_Fecha_Modifica { get; set; }
        public int Hote_Estado { get; set; }
        public int Hote_Telefono { get; set; }
        public string Hote_Correo { get; set; }
        public string Hote_Reseña { get; set; }
        [NotMapped]
        public string Ciud_Descripcion { get; set; }
        [NotMapped]
        public string Esta_Descripcion { get; set; }
        [NotMapped]
        public string Pais_Descripcion { get; set; }
        [NotMapped]
        public double HaHo_PrecioPorNoche { get; set; }
        [NotMapped]
        public double Pais_PorcentajeImpuesto { get; set; }
        [NotMapped]
        public string Impu_Descripcion { get; set; }
        [NotMapped]
        public int Impu_Id { get; set; }
        [NotMapped]
        public int NumeroReservaciones { get; set; }

        public virtual tbUsuarios Hote_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Hote_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbHabitacionesCategorias> tbHabitacionesCategorias { get; set; }
    }
}