// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbMetodosPagos
    {
        public tbMetodosPagos()
        {
            tbFacturas = new HashSet<tbFacturas>();
        }

        public int Meto_Id { get; set; }
        public string Meto_Descripcion { get; set; }
        public int? Meto_Usua_Creacion { get; set; }
        public DateTime? Meto_Fecha_Creacion { get; set; }
        public int? Meto_Usua_Modifica { get; set; }
        public DateTime? Meto_Fecha_Modifica { get; set; }

        public virtual tbUsuarios Meto_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Meto_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturas { get; set; }
    }
}