// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbPaises
    {
        public tbPaises()
        {
            tbEstados = new HashSet<tbEstados>();
        }

        public int Pais_Id { get; set; }
        public string Pais_Descripcion { get; set; }
        public int? Pais_Usua_Creacion { get; set; }
        public DateTime? Pais_Fecha_Creacion { get; set; }
        public int? Pais_Usua_Modifica { get; set; }
        public DateTime? Pais_Fecha_Modifica { get; set; }

        public virtual tbUsuarios Pais_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Pais_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbEstados> tbEstados { get; set; }
    }
}