// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbPaquetes
    {
        public tbPaquetes()
        {
            tbDetallePorPaquete = new HashSet<tbDetallePorPaquete>();
            tbFacturasDetalles = new HashSet<tbFacturasDetalles>();
            tbReservaciones = new HashSet<tbReservaciones>();
            tbViajes = new HashSet<tbViajes>();
        }

        public int Paqu_Id { get; set; }
        public string Paqu_Nombre { get; set; }
        public int Pers_Id { get; set; }
        public int Paqu_Usua_Creacion { get; set; }
        public DateTime Paqu_Fecha_Creacion { get; set; }
        public int? Paqu_Usua_Modifica { get; set; }
        public DateTime? Paqu_Fecha_Modifica { get; set; }
        public int Paqu_Estado { get; set; }
        public decimal Paqu_Precio { get; set; }

        public virtual ICollection<tbDetallePorPaquete> tbDetallePorPaquete { get; set; }
        public virtual ICollection<tbFacturasDetalles> tbFacturasDetalles { get; set; }
        public virtual ICollection<tbReservaciones> tbReservaciones { get; set; }
        public virtual ICollection<tbViajes> tbViajes { get; set; }
    }
}