// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbPersonas
    {
        public tbPersonas()
        {
            tbFacturas = new HashSet<tbFacturas>();
            tbPaquetes = new HashSet<tbPaquetes>();
            tbPersonasPorTarjetas = new HashSet<tbPersonasPorTarjetas>();
            tbUsuarios = new HashSet<tbUsuarios>();
        }

        public int? Pers_Id { get; set; }
        public string Pers_DNI { get; set; }
        public string Pers_Nombre { get; set; }
        public string Pers_Apellido { get; set; }
        public string Pers_Sexo { get; set; }
        public int? Pers_Telefono { get; set; }
        public int? EsCi_Id { get; set; }
        public string Ciud_Id { get; set; }
        public int? Pers_Usua_Creacion { get; set; }
        public DateTime? Pers_Fecha_Creacion { get; set; }
        public int? Pers_Usua_Modifica { get; set; }
        public DateTime? Pers_Fecha_Modifica { get; set; }
        public bool? Pers_Habilitado { get; set; }
        public string Pers_Pasaporte { get; set; }
        public string? Pers_Email { get; set; }
        public int? Carg_Id { get; set; }

        public virtual tbCargos Carg { get; set; }
        public virtual tbCiudades Ciud { get; set; }
        public virtual tbEstadosCiviles EsCi { get; set; }
        public virtual tbUsuarios Pers_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Pers_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbFacturas> tbFacturas { get; set; }
        public virtual ICollection<tbPaquetes> tbPaquetes { get; set; }
        public virtual ICollection<tbPersonasPorTarjetas> tbPersonasPorTarjetas { get; set; }
        public virtual ICollection<tbUsuarios> tbUsuarios { get; set; }
    }
}