// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbTiposDeCamas
    {
        public tbTiposDeCamas()
        {
            tbHabitaciones = new HashSet<tbHabitaciones>();
        }

        public int TiCa_Id { get; set; }
        public string TiCa_Nombre { get; set; }
        public int TiCa_Usua_Creacion { get; set; }
        public DateTime TiCa_Fecha_Creacion { get; set; }
        public int TiCa_Usua_Modifica { get; set; }
        public DateTime TiCa_Fecha_Modifica { get; set; }

        public virtual tbUsuarios TiCa_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios TiCa_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbHabitaciones> tbHabitaciones { get; set; }
    }
}