// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbTiposTransportes
    {
        public tbTiposTransportes()
        {
            tbTransportes = new HashSet<tbTransportes>();
        }

        public int TiTr_Id { get; set; }
        public string TiTr_Descripcion { get; set; }
        public int TiTr_Usua_Creacion { get; set; }
        public DateTime TiTr_Fecha_Creacion { get; set; }
        public int TiTr_Usua_Modifica { get; set; }
        public DateTime TiTr_Fecha_Modifica { get; set; }
        public bool? TiTr_Estado { get; set; }

        public virtual tbUsuarios TiTr_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios TiTr_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbTransportes> tbTransportes { get; set; }
    }
}