// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbTransportes
    {
        public tbTransportes()
        {
            tbHorariosTransportes = new HashSet<tbHorariosTransportes>();
            tbViajes = new HashSet<tbViajes>();
        }

        public int Tran_Id { get; set; }
        public decimal? Tran_Precio { get; set; }
        public int? TiTr_Id { get; set; }
        public int? Tran_PuntoInicio { get; set; }
        public int? Tran_PuntoFinal { get; set; }
        public int Tran_Usua_Creacion { get; set; }
        public DateTime Tran_Fecha_Creacion { get; set; }
        public int? Tran_Usua_Modifica { get; set; }
        public DateTime? Tran_Fecha_Modifica { get; set; }
        public bool? Tran_Estado { get; set; }
        [NotMapped]
        public string PuntoInicio { get; set; }
        [NotMapped]
        public string HorT_FechaYhora { get; set; }
        [NotMapped]
        public string PuntoFinal { get; set; }
        [NotMapped]
        public string TiTr_Descripcion { get; set; }
        
        [NotMapped]
        public string Ciud_UrlImagen { get; set; }
        [NotMapped]
        public string EsCi_Descripcion { get; set; }
        [NotMapped]
        public string Ciud_Descripcion { get; set; }
        [NotMapped]
        public string NumeroPersonas { get; set; }
        [NotMapped]
        public double Pais_PorcentajeImpuesto { get; set; }
        [NotMapped]
        public string Impu_Descripcion { get; set; }
        [NotMapped]
        public int Impu_Id { get; set; }
        [NotMapped]
        public int? HorT_Id { get; set; }


        public virtual tbTiposTransportes TiTr { get; set; }
        public virtual tbCiudades Tran_PuntoFinalNavigation { get; set; }
        public virtual tbCiudades Tran_PuntoInicioNavigation { get; set; }
        public virtual tbUsuarios Tran_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Tran_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbHorariosTransportes> tbHorariosTransportes { get; set; }
        public virtual ICollection<tbViajes> tbViajes { get; set; }
    }
}