// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbUsuarios
    {
        public tbUsuarios()
        {
            InverseUsua_Usua_CreacionNavigation = new HashSet<tbUsuarios>();
            InverseUsua_Usua_ModificaNavigation = new HashSet<tbUsuarios>();
            tbClientesClie_Usua_CreacionNavigation = new HashSet<tbClientes>();
            tbClientesClie_Usua_ModificaNavigation = new HashSet<tbClientes>();
            tbDetallePorPaqueteDePa_Usua_CreacionNavigation = new HashSet<tbDetallePorPaquete>();
            tbDetallePorPaqueteDePa_Usua_ModificaNavigation = new HashSet<tbDetallePorPaquete>();
            tbEstadosCivilesEsCi_Usua_CreacionNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosCivilesEsCi_Usua_ModificaNavigation = new HashSet<tbEstadosCiviles>();
            tbEstadosEsta_Usua_CreacionNavigation = new HashSet<tbEstados>();
            tbEstadosEsta_Usua_ModificaNavigation = new HashSet<tbEstados>();
            tbHabitacionesHabi_Usua_CreacionNavigation = new HashSet<tbHabitaciones>();
            tbHabitacionesHabi_Usua_ModificaNavigation = new HashSet<tbHabitaciones>();
            tbHotelesHote_Usua_CreacionNavigation = new HashSet<tbHoteles>();
            tbHotelesHote_Usua_ModificaNavigation = new HashSet<tbHoteles>();
            tbPaisesPais_Usua_CreacionNavigation = new HashSet<tbPaises>();
            tbPaisesPais_Usua_ModificaNavigation = new HashSet<tbPaises>();
            tbPantallasPant_Usua_CreacionNavigation = new HashSet<tbPantallas>();
            tbPantallasPant_Usua_ModificaNavigation = new HashSet<tbPantallas>();
            tbPantallasPorRolesParo_Usua_CreacionNavigation = new HashSet<tbPantallasPorRoles>();
            tbPantallasPorRolesParo_Usua_ModificaNavigation = new HashSet<tbPantallasPorRoles>();
            tbPaquetesPaqu_Usua_CreacionNavigation = new HashSet<tbPaquetes>();
            tbPaquetesPaqu_Usua_ModificaNavigation = new HashSet<tbPaquetes>();
            tbRolesRol_Usua_CreacionNavigation = new HashSet<tbRoles>();
            tbRolesRol_Usua_ModificaNavigation = new HashSet<tbRoles>();
            tbTiposDeCamasTiCa_Usua_CreacionNavigation = new HashSet<tbTiposDeCamas>();
            tbTiposDeCamasTiCa_Usua_ModificaNavigation = new HashSet<tbTiposDeCamas>();
            tbTiposTransportesTiTr_Usua_CreacionNavigation = new HashSet<tbTiposTransportes>();
            tbTiposTransportesTiTr_Usua_ModificaNavigation = new HashSet<tbTiposTransportes>();
            tbTransportesTran_Usua_CreacionNavigation = new HashSet<tbTransportes>();
            tbTransportesTran_Usua_ModificaNavigation = new HashSet<tbTransportes>();
        }

        public int Usua_Id { get; set; }
        public string Usua_Usuario { get; set; }
        public string Usua_Contra { get; set; }
        public bool? Usua_Admin { get; set; }
        public int? Rol_Id { get; set; }
        public int? Usua_Usua_Creacion { get; set; }
        public DateTime? Usua_Fecha_Creacion { get; set; }
        public int? Usua_Usua_Modifica { get; set; }
        public DateTime? Usua_Fecha_Modifica { get; set; }
        public bool? Usua_Estado { get; set; }
        public int? Clie_Id { get; set; }

        public virtual tbClientes Clie { get; set; }
        public virtual tbRoles Rol { get; set; }
        public virtual tbUsuarios Usua_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Usua_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbUsuarios> InverseUsua_Usua_CreacionNavigation { get; set; }
        public virtual ICollection<tbUsuarios> InverseUsua_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientesClie_Usua_CreacionNavigation { get; set; }
        public virtual ICollection<tbClientes> tbClientesClie_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbDetallePorPaquete> tbDetallePorPaqueteDePa_Usua_CreacionNavigation { get; set; }
        public virtual ICollection<tbDetallePorPaquete> tbDetallePorPaqueteDePa_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesEsCi_Usua_CreacionNavigation { get; set; }
        public virtual ICollection<tbEstadosCiviles> tbEstadosCivilesEsCi_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbEstados> tbEstadosEsta_Usua_CreacionNavigation { get; set; }
        public virtual ICollection<tbEstados> tbEstadosEsta_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbHabitaciones> tbHabitacionesHabi_Usua_CreacionNavigation { get; set; }
        public virtual ICollection<tbHabitaciones> tbHabitacionesHabi_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbHoteles> tbHotelesHote_Usua_CreacionNavigation { get; set; }
        public virtual ICollection<tbHoteles> tbHotelesHote_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbPaises> tbPaisesPais_Usua_CreacionNavigation { get; set; }
        public virtual ICollection<tbPaises> tbPaisesPais_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasPant_Usua_CreacionNavigation { get; set; }
        public virtual ICollection<tbPantallas> tbPantallasPant_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesParo_Usua_CreacionNavigation { get; set; }
        public virtual ICollection<tbPantallasPorRoles> tbPantallasPorRolesParo_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbPaquetes> tbPaquetesPaqu_Usua_CreacionNavigation { get; set; }
        public virtual ICollection<tbPaquetes> tbPaquetesPaqu_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesRol_Usua_CreacionNavigation { get; set; }
        public virtual ICollection<tbRoles> tbRolesRol_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbTiposDeCamas> tbTiposDeCamasTiCa_Usua_CreacionNavigation { get; set; }
        public virtual ICollection<tbTiposDeCamas> tbTiposDeCamasTiCa_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbTiposTransportes> tbTiposTransportesTiTr_Usua_CreacionNavigation { get; set; }
        public virtual ICollection<tbTiposTransportes> tbTiposTransportesTiTr_Usua_ModificaNavigation { get; set; }
        public virtual ICollection<tbTransportes> tbTransportesTran_Usua_CreacionNavigation { get; set; }
        public virtual ICollection<tbTransportes> tbTransportesTran_Usua_ModificaNavigation { get; set; }
    }
}