// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace Agencia.Entities.Entities
{
    public partial class tbViajes
    {
        public int Viaj_Id { get; set; }
        public decimal Viaj_Precio { get; set; }
        public int Viaj_Cantidad { get; set; }
        public int? HorT_Id { get; set; }
        public int? Tran_Id { get; set; }
        public int? Paqu_Id { get; set; }
        public int? Viaj_Usua_Creacion { get; set; }
        public DateTime? Viaj_Fecha_Creacion { get; set; }
        public int? Viaj_Usua_Modifica { get; set; }
        public DateTime? Viaj_Fecha_Modifica { get; set; }

        public virtual tbPaquetes Paqu { get; set; }
        public virtual tbTransportes Tran { get; set; }
        public virtual tbUsuarios Viaj_Usua_CreacionNavigation { get; set; }
        public virtual tbUsuarios Viaj_Usua_ModificaNavigation { get; set; }
    }
}