// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Agencia.DataAcces;
using Agencia.Entities.Entities;

#nullable disable

namespace Agencia.DataAcces.Context
{
    public partial class AgenciadbContext : DbContext
    {
        public AgenciadbContext()
        {
        }

        public AgenciadbContext(DbContextOptions<AgenciadbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tbAirbnbs> tbAirbnbs { get; set; }
        public virtual DbSet<tbCargos> tbCargos { get; set; }
        public virtual DbSet<tbCiudades> tbCiudades { get; set; }
        public virtual DbSet<tbDetallePorPaquete> tbDetallePorPaquete { get; set; }
        public virtual DbSet<tbEstados> tbEstados { get; set; }
        public virtual DbSet<tbEstadosCiviles> tbEstadosCiviles { get; set; }
        public virtual DbSet<tbFacturas> tbFacturas { get; set; }
        public virtual DbSet<tbFacturasDetalles> tbFacturasDetalles { get; set; }
        public virtual DbSet<tbFotografiasPorAirbnbs> tbFotografiasPorAirbnbs { get; set; }
        public virtual DbSet<tbFotografiasPorHabitacion> tbFotografiasPorHabitacion { get; set; }
        public virtual DbSet<tbFotografiasPorHabitacion2> tbFotografiasPorHabitacion2 { get; set; }
        public virtual DbSet<tbHabitaciones> tbHabitaciones { get; set; }
        public virtual DbSet<tbHabitacionesCategorias> tbHabitacionesCategorias { get; set; }
        public virtual DbSet<tbHabitacionesPorHotel> tbHabitacionesPorHotel { get; set; }
        public virtual DbSet<tbHorariosTransportes> tbHorariosTransportes { get; set; }
        public virtual DbSet<tbHoteles> tbHoteles { get; set; }
        public virtual DbSet<tbImpuestos> tbImpuestos { get; set; }
        public virtual DbSet<tbMetodosPagos> tbMetodosPagos { get; set; }
        public virtual DbSet<tbPagosTarjetas> tbPagosTarjetas { get; set; }
        public virtual DbSet<tbPaises> tbPaises { get; set; }
        public virtual DbSet<tbPantallas> tbPantallas { get; set; }
        public virtual DbSet<tbPantallasPorRoles> tbPantallasPorRoles { get; set; }
        public virtual DbSet<tbPaquetes> tbPaquetes { get; set; }
        public virtual DbSet<tbPersonas> tbPersonas { get; set; }
        public virtual DbSet<tbPersonasPorTarjetas> tbPersonasPorTarjetas { get; set; }
        public virtual DbSet<tbReservaciones> tbReservaciones { get; set; }
        public virtual DbSet<tbRoles> tbRoles { get; set; }
        public virtual DbSet<tbTiposDeCamas> tbTiposDeCamas { get; set; }
        public virtual DbSet<tbTiposTransportes> tbTiposTransportes { get; set; }
        public virtual DbSet<tbTransportes> tbTransportes { get; set; }
        public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }
        public virtual DbSet<tbViajes> tbViajes { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<tbAirbnbs>(entity =>
            {
                entity.HasKey(e => e.Airb_Id)
                    .HasName("PK__tbAirbnb__6419FEBFE0970E63");

                entity.ToTable("tbAirbnbs", "Agen");

                entity.Property(e => e.Airb_Correo)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Airb_DireccionExacta)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Airb_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Airb_Fecha_Modifica).HasColumnType("datetime");

                entity.Property(e => e.Airb_Imagen)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.Airb_Nombre)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Airb_Precio).HasColumnType("numeric(8, 2)");

                entity.Property(e => e.Airb_PrecioTodoIncluido).HasColumnType("numeric(8, 2)");

                entity.Property(e => e.Airb_Resena)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Ciud_Id)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.HasOne(d => d.Airb_Usua_CreacionNavigation)
                    .WithMany(p => p.tbAirbnbsAirb_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Airb_Usua_Creacion);

                entity.HasOne(d => d.Airb_Usua_ModificaNavigation)
                    .WithMany(p => p.tbAirbnbsAirb_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Airb_Usua_Modifica);
            });

            modelBuilder.Entity<tbCargos>(entity =>
            {
                entity.HasKey(e => e.Carg_Id)
                    .HasName("PK__tbCargos__B0D859FA60A1E41A");

                entity.ToTable("tbCargos", "Gral");

                entity.Property(e => e.Carg_Descripcion)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Carg_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Carg_Fecha_Modifica).HasColumnType("datetime");

                entity.HasOne(d => d.Carg_Usua_CreacionNavigation)
                    .WithMany(p => p.tbCargosCarg_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Carg_Usua_Creacion);

                entity.HasOne(d => d.Carg_Usua_ModificaNavigation)
                    .WithMany(p => p.tbCargosCarg_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Carg_Usua_Modifica);
            });

            modelBuilder.Entity<tbCiudades>(entity =>
            {
                entity.HasKey(e => e.Ciud_Id)
                    .HasName("PK__tbCiudades__6B07AA3C63FA00C3");

                entity.ToTable("tbCiudades", "Gral");

                entity.Property(e => e.Ciud_Codigo)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.Property(e => e.Ciud_Descripcion)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Ciud_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Ciud_Fecha_Modifica).HasColumnType("datetime");

                entity.Property(e => e.Ciud_UrlImagen).IsUnicode(false);
            });

            modelBuilder.Entity<tbDetallePorPaquete>(entity =>
            {
                entity.HasKey(e => e.DePa_Id)
                    .HasName("PK__tbDetall__942F64275D192EBE");

                entity.ToTable("tbDetallePorPaquete", "Agen");

                entity.Property(e => e.DePa_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.DePa_Fecha_Modifica).HasColumnType("datetime");

                entity.Property(e => e.DePa_Precio).HasColumnType("numeric(8, 2)");

                entity.Property(e => e.DePa_PrecioTodoIncluido)
                    .HasColumnType("numeric(8, 2)")
                    .HasDefaultValueSql("((0))");

                entity.HasOne(d => d.DePa_Usua_CreacionNavigation)
                    .WithMany(p => p.tbDetallePorPaqueteDePa_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.DePa_Usua_Creacion);

                entity.HasOne(d => d.DePa_Usua_ModificaNavigation)
                    .WithMany(p => p.tbDetallePorPaqueteDePa_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.DePa_Usua_Modifica);

                entity.HasOne(d => d.Paqu)
                    .WithMany(p => p.tbDetallePorPaquete)
                    .HasForeignKey(d => d.Paqu_Id);
            });

            modelBuilder.Entity<tbEstados>(entity =>
            {
                entity.HasKey(e => e.Esta_Id)
                    .HasName("PK__tbEstados__72ABC2CCA10E38B9");

                entity.ToTable("tbEstados", "Gral");

                entity.Property(e => e.Esta_Codigo)
                    .IsRequired()
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.Esta_Descripcion)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Esta_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Esta_Fecha_Modifica).HasColumnType("datetime");

                entity.HasOne(d => d.Esta_Usua_CreacionNavigation)
                    .WithMany(p => p.tbEstadosEsta_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Esta_Usua_Creacion);

                entity.HasOne(d => d.Esta_Usua_ModificaNavigation)
                    .WithMany(p => p.tbEstadosEsta_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Esta_Usua_Modifica);

                entity.HasOne(d => d.Pais)
                    .WithMany(p => p.tbEstados)
                    .HasForeignKey(d => d.Pais_Id);
            });

            modelBuilder.Entity<tbEstadosCiviles>(entity =>
            {
                entity.HasKey(e => e.EsCi_Id)
                    .HasName("PK__tbEstado__D52AE7B8BF765F21");

                entity.ToTable("tbEstadosCiviles", "Gral");

                entity.Property(e => e.EsCi_Descripcion)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.EsCi_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.EsCi_Fecha_Modifica).HasColumnType("datetime");

                entity.HasOne(d => d.EsCi_Usua_CreacionNavigation)
                    .WithMany(p => p.tbEstadosCivilesEsCi_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.EsCi_Usua_Creacion)
                    .HasConstraintName("FK_tbEstadosCiviles_tbUsuarios_Esta_Usua_Creacion");

                entity.HasOne(d => d.EsCi_Usua_ModificaNavigation)
                    .WithMany(p => p.tbEstadosCivilesEsCi_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.EsCi_Usua_Modifica)
                    .HasConstraintName("FK_tbEstadosCiviles_tbUsuarios_Esta_Usua_Modifica");
            });

            modelBuilder.Entity<tbFacturas>(entity =>
            {
                entity.HasKey(e => e.Fact_Id)
                    .HasName("PK__tbFactur__8327E0278287225F");

                entity.ToTable("tbFacturas", "Vent");

                entity.Property(e => e.Fact_Fecha).HasColumnType("datetime");

                entity.Property(e => e.Fact_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Fact_Fecha_Modifica).HasColumnType("datetime");

                entity.HasOne(d => d.Fact_Usua_CreacionNavigation)
                    .WithMany(p => p.tbFacturasFact_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Fact_Usua_Creacion);

                entity.HasOne(d => d.Fact_Usua_ModificaNavigation)
                    .WithMany(p => p.tbFacturasFact_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Fact_Usua_Modifica);

                entity.HasOne(d => d.Meto)
                    .WithMany(p => p.tbFacturas)
                    .HasForeignKey(d => d.Meto_Id);

                entity.HasOne(d => d.Pers)
                    .WithMany(p => p.tbFacturas)
                    .HasForeignKey(d => d.Pers_Id);
            });

            modelBuilder.Entity<tbFacturasDetalles>(entity =>
            {
                entity.HasKey(e => e.Fdet_Id)
                    .HasName("PK__tbFactur__0E93E9FFEF45D039");

                entity.ToTable("tbFacturasDetalles", "Vent");

                entity.HasOne(d => d.Fact)
                    .WithMany(p => p.tbFacturasDetalles)
                    .HasForeignKey(d => d.Fact_Id);

                entity.HasOne(d => d.Paqu)
                    .WithMany(p => p.tbFacturasDetalles)
                    .HasForeignKey(d => d.Paqu_Id);
            });

            modelBuilder.Entity<tbFotografiasPorAirbnbs>(entity =>
            {
                entity.HasKey(e => e.FoAi_Id)
                    .HasName("PK__tbFotogr__A0B70F2B6BE7AE3E");

                entity.ToTable("tbFotografiasPorAirbnbs", "Agen");

                entity.Property(e => e.FoAi_UrlImagen).IsUnicode(false);

                entity.HasOne(d => d.Airb)
                    .WithMany(p => p.tbFotografiasPorAirbnbs)
                    .HasForeignKey(d => d.Airb_Id);
            });

            modelBuilder.Entity<tbFotografiasPorHabitacion>(entity =>
            {
                entity.HasKey(e => e.FoHa_Id)
                    .HasName("PK__tbFotogr__FFC6D99EC6DD7F69");

                entity.ToTable("tbFotografiasPorHabitacion", "Agen");

                entity.Property(e => e.FoHa_UrlImagen)
                    .IsRequired()
                    .IsUnicode(false);

                entity.HasOne(d => d.HaHo)
                    .WithMany(p => p.tbFotografiasPorHabitacion)
                    .HasForeignKey(d => d.HaHo_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbFotografiasPorHabitacion2>(entity =>
            {
                entity.HasKey(e => e.FoHa_Id);

                entity.ToTable("tbFotografiasPorHabitacion2", "Agen");

                entity.Property(e => e.FoHa_UrlImagen)
                    .IsRequired()
                    .IsUnicode(false);

                entity.HasOne(d => d.HaCa)
                    .WithMany(p => p.tbFotografiasPorHabitacion2)
                    .HasForeignKey(d => d.HaCa_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__tbFotogra__HaCa___0AF29B96");
            });

            modelBuilder.Entity<tbHabitaciones>(entity =>
            {
                entity.HasKey(e => e.Habi_Id)
                    .HasName("PK__tbHabita__9183576E9AFFDAEA");

                entity.ToTable("tbHabitaciones", "Agen");

                entity.Property(e => e.Habi_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Habi_Fecha_Modifica).HasColumnType("datetime");

                entity.HasOne(d => d.Habi_Usua_CreacionNavigation)
                    .WithMany(p => p.tbHabitacionesHabi_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Habi_Usua_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Habi_Usua_ModificaNavigation)
                    .WithMany(p => p.tbHabitacionesHabi_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Habi_Usua_Modifica);

                entity.HasOne(d => d.TiCa)
                    .WithMany(p => p.tbHabitaciones)
                    .HasForeignKey(d => d.TiCa_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbHabitaciones_TiCa_Id");
            });

            modelBuilder.Entity<tbHabitacionesCategorias>(entity =>
            {
                entity.HasKey(e => e.HaCa_Id)
                    .HasName("PK__Habitaci__522C2094655A1D18");

                entity.ToTable("tbHabitacionesCategorias", "Agen");

                entity.Property(e => e.HaCa_Nombre)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.HaCa_PrecioPorNoche).HasColumnType("numeric(8, 2)");

                entity.HasOne(d => d.Habi)
                    .WithMany(p => p.tbHabitacionesCategorias)
                    .HasForeignKey(d => d.Habi_Id)
                    .HasConstraintName("FK__tbHabitac__Habi___0BE6BFCF");

                entity.HasOne(d => d.Hote)
                    .WithMany(p => p.tbHabitacionesCategorias)
                    .HasForeignKey(d => d.Hote_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Habitacio__Hote___08162EEB");
            });

            modelBuilder.Entity<tbHabitacionesPorHotel>(entity =>
            {
                entity.HasKey(e => e.HaHo_Id)
                    .HasName("PK__tbHabita__352A772C0DD89EAD");

                entity.ToTable("tbHabitacionesPorHotel", "Agen");

                entity.Property(e => e.HaHo_Numero)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.HasOne(d => d.HaCa)
                    .WithMany(p => p.tbHabitacionesPorHotel)
                    .HasForeignKey(d => d.HaCa_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbHorariosTransportes>(entity =>
            {
                entity.HasKey(e => e.HorT_Id)
                    .HasName("PK__tbHorari__8EB94D98CFDF1477");

                entity.ToTable("tbHorariosTransportes", "Agen");

                entity.Property(e => e.HorT_FechaYhora).HasColumnType("datetime");

                entity.HasOne(d => d.Tran)
                    .WithMany(p => p.tbHorariosTransportes)
                    .HasForeignKey(d => d.Tran_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_tbHorariosTransportes_tbTransportes");
            });

            modelBuilder.Entity<tbHoteles>(entity =>
            {
                entity.HasKey(e => e.Hote_Id)
                    .HasName("PK__tbHotele__297BB723495D4888");

                entity.ToTable("tbHoteles", "Agen");

                entity.Property(e => e.Ciud_Id)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.Property(e => e.Hote_DireccionExacta)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Hote_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Hote_Fecha_Modifica).HasColumnType("datetime");

                entity.Property(e => e.Hote_Imagen)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.Hote_Nombre)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Hote_PrecioTodoIncluido).HasColumnType("numeric(8, 2)");

                entity.Property(e => e.Hote_Reseña)
                    .HasMaxLength(250)
                    .IsUnicode(false);

                entity.HasOne(d => d.Hote_Usua_CreacionNavigation)
                    .WithMany(p => p.tbHotelesHote_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Hote_Usua_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Hote_Usua_ModificaNavigation)
                    .WithMany(p => p.tbHotelesHote_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Hote_Usua_Modifica);
            });

            modelBuilder.Entity<tbImpuestos>(entity =>
            {
                entity.HasKey(e => e.Impu_Id)
                    .HasName("PK__tbImpues__23E8CC887EDF9CB6");

                entity.ToTable("tbImpuestos", "Gral");

                entity.Property(e => e.Impu_Descripcion)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Impu_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Impu_Fecha_Modifica).HasColumnType("datetime");

                entity.HasOne(d => d.Impu_Usua_CreacionNavigation)
                    .WithMany(p => p.tbImpuestosImpu_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Impu_Usua_Creacion);

                entity.HasOne(d => d.Impu_Usua_ModificaNavigation)
                    .WithMany(p => p.tbImpuestosImpu_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Impu_Usua_Modifica);
            });

            modelBuilder.Entity<tbMetodosPagos>(entity =>
            {
                entity.HasKey(e => e.Meto_Id)
                    .HasName("PK__tbMetodo__DC2F63652C1F7CB8");

                entity.ToTable("tbMetodosPagos", "Gral");

                entity.Property(e => e.Meto_Descripcion)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Meto_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Meto_Fecha_Modifica).HasColumnType("datetime");

                entity.HasOne(d => d.Meto_Usua_CreacionNavigation)
                    .WithMany(p => p.tbMetodosPagosMeto_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Meto_Usua_Creacion);

                entity.HasOne(d => d.Meto_Usua_ModificaNavigation)
                    .WithMany(p => p.tbMetodosPagosMeto_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Meto_Usua_Modifica);
            });

            modelBuilder.Entity<tbPagosTarjetas>(entity =>
            {
                entity.HasKey(e => e.PaTa_Id)
                    .HasName("PK__tbPagosT__8DD0FDBA889821A2");

                entity.ToTable("tbPagosTarjetas", "Vent");

                entity.Property(e => e.PaTa_AnhioVencimiento)
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.Property(e => e.PaTa_Descripcion)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.PaTa_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.PaTa_Fecha_Modifica).HasColumnType("datetime");

                entity.Property(e => e.PaTa_MesVencimiento)
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.PaTa_NombrePropietario)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.PaTa_NumeroTarjeta)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasOne(d => d.PaTa_Usua_CreacionNavigation)
                    .WithMany(p => p.tbPagosTarjetasPaTa_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.PaTa_Usua_Creacion);

                entity.HasOne(d => d.PaTa_Usua_ModificaNavigation)
                    .WithMany(p => p.tbPagosTarjetasPaTa_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.PaTa_Usua_Modifica);
            });

            modelBuilder.Entity<tbPaises>(entity =>
            {
                entity.HasKey(e => e.Pais_Id)
                    .HasName("PK__tbPaises__6356B8333AC60BDA");

                entity.ToTable("tbPaises", "Gral");

                entity.Property(e => e.Pais_Descripcion)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Pais_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Pais_Fecha_Modifica).HasColumnType("datetime");

                entity.HasOne(d => d.Impu)
                    .WithMany(p => p.tbPaises)
                    .HasForeignKey(d => d.Impu_Id);

                entity.HasOne(d => d.Pais_Usua_CreacionNavigation)
                    .WithMany(p => p.tbPaisesPais_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Pais_Usua_Creacion)
                    .HasConstraintName("FK_tbPais_tbUsuarios_Pais_Usua_Creacion");

                entity.HasOne(d => d.Pais_Usua_ModificaNavigation)
                    .WithMany(p => p.tbPaisesPais_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Pais_Usua_Modifica)
                    .HasConstraintName("FK_tbPias_tbUsuarios_Pais_Usua_Modifca");
            });

            modelBuilder.Entity<tbPantallas>(entity =>
            {
                entity.HasKey(e => e.Pant_Id)
                    .HasName("PK__tbPantal__CF98C93254D737DD");

                entity.ToTable("tbPantallas", "Acce");

                entity.Property(e => e.Pant_Descripcion)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Pant_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Pant_Fecha_Modifica).HasColumnType("datetime");

                entity.HasOne(d => d.Pant_Usua_CreacionNavigation)
                    .WithMany(p => p.tbPantallasPant_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Pant_Usua_Creacion);

                entity.HasOne(d => d.Pant_Usua_ModificaNavigation)
                    .WithMany(p => p.tbPantallasPant_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Pant_Usua_Modifica);
            });

            modelBuilder.Entity<tbPantallasPorRoles>(entity =>
            {
                entity.HasKey(e => e.Paro_Id)
                    .HasName("PK__tbPantal__53819DE90C8B2039");

                entity.ToTable("tbPantallasPorRoles", "Acce");

                entity.Property(e => e.Paro_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Paro_Fecha_Modifica).HasColumnType("datetime");

                entity.HasOne(d => d.Pant)
                    .WithMany(p => p.tbPantallasPorRoles)
                    .HasForeignKey(d => d.Pant_Id);

                entity.HasOne(d => d.Paro_Usua_CreacionNavigation)
                    .WithMany(p => p.tbPantallasPorRolesParo_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Paro_Usua_Creacion);

                entity.HasOne(d => d.Paro_Usua_ModificaNavigation)
                    .WithMany(p => p.tbPantallasPorRolesParo_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Paro_Usua_Modifica);

                entity.HasOne(d => d.Rol)
                    .WithMany(p => p.tbPantallasPorRoles)
                    .HasForeignKey(d => d.Rol_Id);
            });

            modelBuilder.Entity<tbPaquetes>(entity =>
            {
                entity.HasKey(e => e.Paqu_Id)
                    .HasName("PK__tbPaquet__39E5493D4D6EB5A2");

                entity.ToTable("tbPaquetes", "Agen");

                entity.HasIndex(e => e.Paqu_Nombre, "UQ_tbPaquetes_Paqu_Nombre")
                    .IsUnique();

                entity.Property(e => e.Paqu_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Paqu_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Paqu_Fecha_Modifica).HasColumnType("datetime");

                entity.Property(e => e.Paqu_Nombre)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Paqu_Precio).HasColumnType("numeric(8, 2)");
            });

            modelBuilder.Entity<tbPersonas>(entity =>
            {
                entity.HasKey(e => e.Pers_Id)
                    .HasName("PK__tbClient__5BB95503F4A2DA75");

                entity.ToTable("tbPersonas", "Gral");

                entity.HasIndex(e => e.Pers_DNI, "UQ_tbPersonas_Pers_DNI")
                    .IsUnique();

                entity.HasIndex(e => e.Pers_Pasaporte, "UQ_tbPersonas_Pers_Pasaporte")
                    .IsUnique();

                entity.HasIndex(e => e.Pers_Telefono, "UQ_tbPersonas_Pers_Telefono")
                    .IsUnique();

                entity.Property(e => e.Carg_Id).HasDefaultValueSql("((1))");

                entity.Property(e => e.Ciud_Id)
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.Property(e => e.Pers_Apellido)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Pers_DNI)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Pers_Email)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Pers_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Pers_Fecha_Modifica).HasColumnType("datetime");

                entity.Property(e => e.Pers_Nombre)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Pers_Pasaporte)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.Pers_Sexo)
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.HasOne(d => d.Carg)
                    .WithMany(p => p.tbPersonas)
                    .HasForeignKey(d => d.Carg_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.EsCi)
                    .WithMany(p => p.tbPersonas)
                    .HasForeignKey(d => d.EsCi_Id)
                    .HasConstraintName("FK_tbClientes_tbEstadosCiviles_EsCi_Id");

                entity.HasOne(d => d.Pers_Usua_CreacionNavigation)
                    .WithMany(p => p.tbPersonasPers_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Pers_Usua_Creacion)
                    .HasConstraintName("FK_tbClientes_tbUsuarios_Clie_Usua_Creacion");

                entity.HasOne(d => d.Pers_Usua_ModificaNavigation)
                    .WithMany(p => p.tbPersonasPers_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Pers_Usua_Modifica)
                    .HasConstraintName("FK_tbClientes_tbUsuarios_Clie_Usua_Modifica");
            });

            modelBuilder.Entity<tbPersonasPorTarjetas>(entity =>
            {
                entity.HasKey(e => e.PeTa_Id)
                    .HasName("PK__tbPerson__CEEDCF3DA6D45446");

                entity.ToTable("tbPersonasPorTarjetas", "Vent");

                entity.HasOne(d => d.PaTa)
                    .WithMany(p => p.tbPersonasPorTarjetas)
                    .HasForeignKey(d => d.PaTa_Id);

                entity.HasOne(d => d.Pers)
                    .WithMany(p => p.tbPersonasPorTarjetas)
                    .HasForeignKey(d => d.Pers_Id);
            });

            modelBuilder.Entity<tbReservaciones>(entity =>
            {
                entity.HasKey(e => e.Rese_Id)
                    .HasName("PK__tbReserv__72CC329EE19E75DE");

                entity.ToTable("tbReservaciones", "Agen");

                entity.Property(e => e.Rese_FechaEntrada).HasColumnType("date");

                entity.Property(e => e.Rese_FechaSalida).HasColumnType("date");

                entity.Property(e => e.Rese_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Rese_Fecha_Modifica).HasColumnType("datetime");

                entity.Property(e => e.Rese_Observacion)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.Rese_Precio).HasColumnType("numeric(8, 2)");

                entity.Property(e => e.Rese_PrecioTodoIncluido).HasColumnType("numeric(8, 2)");

                entity.HasOne(d => d.HaHo)
                    .WithMany(p => p.tbReservaciones)
                    .HasForeignKey(d => d.HaHo_Id);

                entity.HasOne(d => d.Paqu)
                    .WithMany(p => p.tbReservaciones)
                    .HasForeignKey(d => d.Paqu_Id);

                entity.HasOne(d => d.Rese_Usua_CreacionNavigation)
                    .WithMany(p => p.tbReservacionesRese_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Rese_Usua_Creacion);

                entity.HasOne(d => d.Rese_Usua_ModificaNavigation)
                    .WithMany(p => p.tbReservacionesRese_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Rese_Usua_Modifica);
            });

            modelBuilder.Entity<tbRoles>(entity =>
            {
                entity.HasKey(e => e.Rol_Id)
                    .HasName("PK__tbRoles__795EBD49E2DD24DB");

                entity.ToTable("tbRoles", "Acce");

                entity.Property(e => e.Rol_Descripcion)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.Rol_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Rol_Fecha_Modifica).HasColumnType("datetime");

                entity.HasOne(d => d.Rol_Usua_CreacionNavigation)
                    .WithMany(p => p.tbRolesRol_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Rol_Usua_Creacion);

                entity.HasOne(d => d.Rol_Usua_ModificaNavigation)
                    .WithMany(p => p.tbRolesRol_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Rol_Usua_Modifica);
            });

            modelBuilder.Entity<tbTiposDeCamas>(entity =>
            {
                entity.HasKey(e => e.TiCa_Id)
                    .HasName("PK__tbTiposD__8D3B85D24A4E81BD");

                entity.ToTable("tbTiposDeCamas", "Gral");

                entity.Property(e => e.TiCa_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.TiCa_Fecha_Modifica).HasColumnType("datetime");

                entity.Property(e => e.TiCa_Nombre)
                    .HasMaxLength(100)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<tbTiposTransportes>(entity =>
            {
                entity.HasKey(e => e.TiTr_Id)
                    .HasName("PK__tbTiposT__A09FE04BE09CB252");

                entity.ToTable("tbTiposTransportes", "Gral");

                entity.Property(e => e.TiTr_Descripcion)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.TiTr_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.TiTr_Fecha_Modifica).HasColumnType("datetime");

                entity.HasOne(d => d.TiTr_Usua_CreacionNavigation)
                    .WithMany(p => p.tbTiposTransportesTiTr_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.TiTr_Usua_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.TiTr_Usua_ModificaNavigation)
                    .WithMany(p => p.tbTiposTransportesTiTr_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.TiTr_Usua_Modifica)
                    .HasConstraintName("FK_tbTiposTransportes_tbUsuarios_TiTr_Usua_Modifca");
            });

            modelBuilder.Entity<tbTransportes>(entity =>
            {
                entity.HasKey(e => e.Tran_Id)
                    .HasName("PK__tbTransp__950EE6B0AE77E54B");

                entity.ToTable("tbTransportes", "Agen");

                entity.Property(e => e.Tran_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Tran_Fecha_Modifica).HasColumnType("datetime");

                entity.Property(e => e.Tran_Precio).HasColumnType("numeric(8, 2)");

                entity.HasOne(d => d.TiTr)
                    .WithMany(p => p.tbTransportes)
                    .HasForeignKey(d => d.TiTr_Id);

                entity.HasOne(d => d.Tran_PuntoFinalNavigation)
                    .WithMany(p => p.tbTransportesTran_PuntoFinalNavigation)
                    .HasForeignKey(d => d.Tran_PuntoFinal);

                entity.HasOne(d => d.Tran_PuntoInicioNavigation)
                    .WithMany(p => p.tbTransportesTran_PuntoInicioNavigation)
                    .HasForeignKey(d => d.Tran_PuntoInicio);

                entity.HasOne(d => d.Tran_Usua_CreacionNavigation)
                    .WithMany(p => p.tbTransportesTran_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Tran_Usua_Creacion)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Tran_Usua_ModificaNavigation)
                    .WithMany(p => p.tbTransportesTran_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Tran_Usua_Modifica)
                    .HasConstraintName("FK_tbTransportes_tbUsuarios_Tran_Usua_Modifca");
            });

            modelBuilder.Entity<tbUsuarios>(entity =>
            {
                entity.HasKey(e => e.Usua_Id)
                    .HasName("PK__tbUsuari__E863C8EE16400214");

                entity.ToTable("tbUsuarios", "Acce");

                entity.Property(e => e.Usua_CodigoVerificacion)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false);

                entity.Property(e => e.Usua_Contra).IsUnicode(false);

                entity.Property(e => e.Usua_Estado).HasDefaultValueSql("((1))");

                entity.Property(e => e.Usua_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Usua_Fecha_Modifica).HasColumnType("datetime");

                entity.Property(e => e.Usua_UrlImagen).IsUnicode(false);

                entity.Property(e => e.Usua_Usuario)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.HasOne(d => d.Pers)
                    .WithMany(p => p.tbUsuarios)
                    .HasForeignKey(d => d.Pers_Id);

                entity.HasOne(d => d.Rol)
                    .WithMany(p => p.tbUsuarios)
                    .HasForeignKey(d => d.Rol_Id);

                entity.HasOne(d => d.Usua_Usua_CreacionNavigation)
                    .WithMany(p => p.InverseUsua_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Usua_Usua_Creacion);

                entity.HasOne(d => d.Usua_Usua_ModificaNavigation)
                    .WithMany(p => p.InverseUsua_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Usua_Usua_Modifica);
            });

            modelBuilder.Entity<tbViajes>(entity =>
            {
                entity.HasKey(e => e.Viaj_Id)
                    .HasName("PK__tbViajes__DAE951F529D52D73");

                entity.ToTable("tbViajes", "Agen");

                entity.Property(e => e.Viaj_Fecha_Creacion).HasColumnType("datetime");

                entity.Property(e => e.Viaj_Fecha_Modifica).HasColumnType("datetime");

                entity.Property(e => e.Viaj_Precio).HasColumnType("numeric(8, 2)");

                entity.HasOne(d => d.Paqu)
                    .WithMany(p => p.tbViajes)
                    .HasForeignKey(d => d.Paqu_Id);

                entity.HasOne(d => d.Tran)
                    .WithMany(p => p.tbViajes)
                    .HasForeignKey(d => d.Tran_Id);

                entity.HasOne(d => d.Viaj_Usua_CreacionNavigation)
                    .WithMany(p => p.tbViajesViaj_Usua_CreacionNavigation)
                    .HasForeignKey(d => d.Viaj_Usua_Creacion);

                entity.HasOne(d => d.Viaj_Usua_ModificaNavigation)
                    .WithMany(p => p.tbViajesViaj_Usua_ModificaNavigation)
                    .HasForeignKey(d => d.Viaj_Usua_Modifica);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}